### ISSUE TITLE
关于图片检索ppt的问题

### ISSUE THREAD

**Issue by superboySB** [BIT-IR/final-project-2019#1]
学长请问，图片检索ppt中相似的定义是指什么?相似是指哪方面的相似?

from 戴子彭

**Comment by nghuyong** [comment]
假设我们有PPT1，PPT2，...，PPT100；一共100个PPT文件
case1 我直接从PPT4中截取整个第3页，作为输入的query，就需要输出文件PPT4，页数3.
case2 我从PPT4中的截取第3页的一部分，比如一个公式的图片，作为输入的query，就需要输出文件PPT4，页数3.
case3 我从网上找了PPT4中第3页公式的一个图片，相似但不一样，作为输入的query，就需要输出文件PPT4，页数3.
至于什么样算相似，有专门的图像相似的数据集，可以看看数据集中的相似的case，以及不相似的case，会有更直观的感受。

**Comment by superboySB** [comment]
学长，我想再确认一下对“图片检索PPT”的理解。是不是分成两部分，匹配或是相似？如果用户截取测试集ppt的一部分页面，系统应该需要找到原本ppt的对应这一页，也就是直接匹配一模一样的；而如果用户随便上网找一个图片，那问题就变成了图片相似问题了。我理解的对吧？

如果对的话，问题就是。用户在用这个系统去寻找一个相似的图片时，应该找图1这样，但我用另一个食物图片来找相似；还是像后两张这样，但我用差不多的矢量图来找相似？很显然，对于用户来说，如果他拿出一个鸡腿图片，那很可能更好地匹配这张鸡腿PPT；但如果他随便拿出一个相似的小人矢量图、或者随便拿出几个箭头的矢量图来，那我首先认为这就不是一个很好的query，且不说它在检索相似图像上几乎没有意义，而且根据矢量图很可能找不到想要的PPT，同样的矢量图会在很多地方都出现。

![微信截图_20191028213904](https://user-images.githubusercontent.com/20726189/67683687-c5e0cf00-f9cc-11e9-89fc-8993757ad9e7.png)
![微信截图_20191028213933](https://user-images.githubusercontent.com/20726189/67683693-c8432900-f9cc-11e9-8254-7abf04717bf6.png)
![微信截图_20191028213735](https://user-images.githubusercontent.com/20726189/67684032-6505c680-f9cd-11e9-922c-6e7b56637291.png)

所以我对需求的理解是，在不考虑同样区域匹配，而就是判断与query相似的PPT这样的场景时，我拿一张带图文PPT去找整个相似的PPT是不符合需求的，更多时候，应该就是拿一张图片作为query来找某PPT里的某一个相似图片，才更实际吧？如果这样的话，那相似图片的选取，是我们的自由吗？例如，PPT最通常出现的图不是那些真实物体（人、车、食物）的图，而是像图2、3这样的矢量图才是最多出现的，但这种矢量图我认为真的不是一个很好的query。

我觉得我们是不是更应该用每个PPT里类似鸡腿这样意义更大的图片来作为我们的dataset呢？

（p.s.我们发现使用像小人、箭头一大堆意义不明的矢量图来做训练集，得到了非常非常非常差的效果。因此想问一下学长，对于相似这一功能的需求，是不是我们想复杂了。其实简单说可能就是一个物体相似检测（image retrieval）问题吧，并且全世界现在最常考虑的应该也是目前COCO、NUS_WIDE的这样主流的物体识别场景。当然，我期望，用一个真实的公交车，能够找到含有公交车图标、公交车icon、公交车简笔画这样的ppt，我觉得还是有可能的。但除此之外，拿一个小人图标、箭头图标等这种PPT出现频率最高的挂件类图片作匹配，着实难以训练。

学长的项目对这种矢量图匹配，是否有很大需求？）

谢谢学长。

**Comment by nghuyong** [comment]
感谢对这个问题的深入讨论！！
回顾一下图片检索PPT设想的初衷，是我们有检索的需求，但是不好用文字表述。比如有一个公式，不太好用文字表述，我可以直接截公式的图片，然后用这个图片去检索PPT。
所以：
1. 对没有意义的矢量图（小人，箭头）是不符合我们设计初衷的，在构建数据集时候，搜索的图片query也不应该是这样无意义的矢量图。
2. 你说的“匹配和相似”本质是一个问题，都是计算相似度，如果一模一样，那相似度就是100%了。
3. 用户检索的query应该和PPT里面高度相似的，否则就是弹出没有找到合适的结果。（通过控制相似度的阈值，低于一定的阈值，返回没有合适的结果）
